apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webstory
  labels:
    app: go-webstory
spec:
  selector:
    matchLabels:
      app: go-webstory
  template:
    metadata:
      labels:
        app: go-webstory
    spec:
      containers:
      - name: go-webstory
        image: go-webstory
        ports:
        - containerPort: 8080