apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webstory
  labels:
    app: go-webstory
spec:
  selector:
    matchLabels:
      app: go-webstory
  template:
    metadata:
      labels:
        app: go-webstory
    spec:
      containers:
      - name: go-webstory
        image: go-webstory
        ports:
        - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: go-webstory
# spec:
#   selector:
#     app: go-webstory
#   ports:
#     - protocol: TCP
#       port: 3000
#       name: web
#       targetPort: 3000
